---
- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: "{{ hostvars[groups['db'][0]].inventory_hostname }}"
  tasks:
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: enable puma
      systemd: name=puma enabled=yes
      tags: app-tag
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
